config/routes.rb
Rails.application.routes.draw do
  resources :carts do
    resources :payments, only: [:create, :new]
    resources :orders, only: [:create]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products do
    resources :line_items
    resources :orders
    collection do
      get 'search'
      post 'search'
    end
  end

  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_one :payment
  has_many :line_items
  has_many :products, through: :line_items
  delegate :name, :price, :description, :inventory, :to => :product, :prefix => true

  def total_price
    total_price = 0
    self.line_items.each do |qty|
      total_price += qty.subtotal
    end
    total_price
  end

  def transaction(stripeToken,stripeEmail)
    begin
      Stripe::Charge.create(
        amount: self.total_price*100,
        currency: "usd",
        source: stripeToken,
        receipt_email: stripeEmail
        )
      self.save
    rescue
      puts "transaction fails"
    end

  end


  def stack_item(product, params)
    self.item_already_exists?(product) ? increase_quantity(params) : add_item(product, params)
    @line_item.save
  end

  def increase_quantity(params)
    @line_item.quantity += params[:line_item][:quantity].to_i
  end

  def add_item(product, params)
    @line_item = LineItem.new(product: product, quantity: params[:line_item][:quantity])
    @line_item.cart = self
  end

  def item_already_exists?(product)
    @line_item = self.line_items.find_by(product: product)
  end

  def self.find_or_create(cart_id, current_user)
    if cart_id == nil
      cart = Cart.create(user: current_user)
      cart_id = cart.id
    else
      cart = Cart.find(cart_id)
    end
    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]


    def show
    end

    def new
      @cart = Cart.new
    end


    def edit
    end

    def create
      @cart = Cart.new

      respond_to do |format|
        if @cart.save
          format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
          format.json { render :show, status: :created, location: @cart }
        else
          format.html { render :new }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /carts/1
    # PATCH/PUT /carts/1.json
    def update
      @cart.transaction(params[:stripeToken],params[:stripeEmail])
      @cart.line_items.destroy_all

      respond_to do |format|
        if @cart.update(cart_params)
          format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
          format.json { render :show, status: :ok, location: @cart }
        else
          format.html { render :edit }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /carts/1
    # DELETE /carts/1.json
    def destroy
      @cart.line_items.destroy_all
      flash[:notice] = "You have cleared your cart"
      redirect_to @cart
    end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<br/>
<br/>
<br/>
<br/>
<main class="container">
    <h1>Shopping Cart</h1>
    <br/>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            <% @cart.line_items.each do |line_item|%>
            <tr>
                <td><%=line_item.product_name%></td>
                <td><%=line_item.quantity %></td>
                <td><%= number_to_currency(discounted_price(current_user, line_item.product_price))%></td>
                <td><%= number_to_currency(discounted_price(current_user, line_item.subtotal))%></td>
            </tr>
            <tr>
              <% end %>
                <td></td>
                <td></td>
                <td>Total Price</td>
                <td>
                    <strong>
                        <%=number_to_currency(discounted_price(current_user, @cart.total_price)) %>
                    </strong>
                    <br/>
                    <br/>
                    <%= link_to 'Check Out',new_cart_payment_path(@cart), class: "btn btn-danger"%>
                    <br/>
                    <br/>
                    <%= link_to 'Clear Cart', cart_path(@cart), method: :delete, class: "btn btn-success" %>
                </td>
            </tr>
        </tbody>
    </table>
</main>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>