config/routes.rb
Rails.application.routes.draw do
  resources :carts do
    resources :payments, only: [:create, :new]
    resources :orders, only: [:create]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products do
    resources :line_items
    resources :orders
    collection do
      get 'search'
      post 'search'
    end
  end

  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name,:description,:price,:inventory, presence: true
  has_one :line_item

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show, :search]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page]).per(20).order('created_at DESC')
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def search
    @searched_value = params[:search]
    # @products  = Product.search(params[:search]).page(params[:page]).per(4).order('created_at')
    @product = Product.where("name LIKE ? OR description LIKE ?",
     "%#{@searched_value}%", "%#{@searched_value}%")
    render 'search'
  end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    render status: 508

    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :inventory)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def discounted_price(user_signed_in, price)
    user_signed_in? ? price * ENV["discounted_price"].to_f : price
  end

end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :inventory %>
    <%= f.number_field :inventory %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<br />
<br />
<br />
<main class="container">
    <br/>
    <p class="container notice"><%= notice %></p>

    <div id="carousel-website" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel-website" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-website" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://i.imgur.com/Bxzy7gX.png" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="http://i.imgur.com/p0JLkrC.png" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carousel-website" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-website" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        <% @products.each do |product| %>

        <section class="col-4">
            <section class="card product-card">
                <section class="card-block">
                    <img class="card-img-top" src="http://placehold.it/250x250" alt="Card image cap">
                    <br/>
                    <br/>
                    <header class="card-title product-name">
                        <%= product.name %>
                    </header>
                    <br/>
                    <section class="card-text product-price">
                      <%= number_to_currency(discounted_price(current_user, product.price)) %>
                    </section>
                    <br/>
                    <section class="card-text product-description">
                        <%= product.description.truncate(100) %>
                    </section>
                    <br/>
                    <%= link_to 'More info', product_path(product), class: "btn btn-outline-primary" %>
                </section>
            </section>
        </section>
        <% end %>
    </div>
    <br/>
    <%= paginate @products %>
</main>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<br />
<br />
<br />
<br />
<main class="container">
<h2>Search Results</h2>
<div class="row search-products">
  <% if @product.present? %>
    <% @product.each do |product| %>
      <section class="col-4">
          <section class="card product-card">
              <section class="card-block">
                  <img class="card-img-top" src="http://placehold.it/250x250" alt="Card image cap">
                  <br/>
                  <br/>
                  <header class="card-title product-name">
                      <%= product.name %>
                  </header>
                  <br/>
                  <section class="card-text product-price">
                    <%= number_to_currency(discounted_price(current_user, product.price)) %>
                  </section>
                  <br/>
                  <section class="card-text product-description">
                      <%= product.description.truncate(100) %>
                  </section>
                  <br/>
                  <%= link_to 'More Info', product_path(product), class: "btn btn-outline-primary" %>
              </section>
          </section>
      </section>
    <% end %>
  <% else %>
    <p>There are no products containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>
</main>

app/views/products/show.html.erb
<br/>
<br/>
<br/>
<br/>
<main class="container">
    <p id="notice"><%= notice %></p>

    <section class="row product-show">
        <section class="col-6">
            <img src="http://placehold.it/500x500" alt="Card image cap">
        </section>

        <section class="col-6">
            <section class="card product-card-page">
                <section class="card-block">
                    <header class="card-title product-name">
                        <h3><%= @product.name %></h3>
                    </header>
                    <br/>
                    <section class="card-text product-price">
                      <%= number_to_currency(discounted_price(current_user, @product.price)) %>
                    </section>
                    <br/>
                    <section class="card-text product-description">
                        <%= @product.description %>
                    </section>
                    <br />
                    <section class="card-text product-inventory">
                      <strong>
                        <%= @product.inventory %> left
                        </strong>
                    </section>
                    <br/>
                    <%= link_to 'Go Back', products_path, class: "btn btn-outline-primary" %>
                    <br/>
                    <br/>
                    <% if @product.inventory > 0 %>
                      <%=bootstrap_form_for [@product, LineItem.new] do |f| %>
                        <%=f.number_field :quantity, min: 1, class: 'col-3' %>
                        <%=f.submit 'Add to cart', class: 'btn btn-danger btn-block' %>
                      <% end %>
                    <% else %>
                      <button class="btn btn-danger btn-block">We're sold out</button>
                    <% end %>
                </section>
            </section>
        </section>
    </section>
</main>
<br/>
<br/>
<br/>